language: go
go:
  - "1.1"
  - "1.2.2"

install:
  - go get -d -v ./...
  - go get -u gopkg.in/check.v1
  - go get code.google.com/p/go.tools/cmd/cover
  - go get -u github.com/mattn/goveralls

script:
  - go test -v ./...
  # - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
